### ISSUE TITLE
[manjaro-hotfixes] wrong polkit rule permission

### ISSUE THREAD

**Issue by udeved** [manjaro/packages-core#23]
It produces several errors when building iso.

    warning: directory permissions differ on /build/manjaro-tools/buildiso/net/x86_64/net-image/etc/polkit-1/rules.d/
    filesystem: 700  package: 750

**Comment by philmmanjaro** [comment]
fixed

**Comment by udeved** [comment]
Shouldn't this package depend on polkit and dbus?

**Comment by philmmanjaro** [comment]
Have to check, never thought of it ...

**Comment by udeved** [comment]
I think, its not nice atm, because it seems to be first package that creates polkit dirs, despite polkit not present.
If you keep it this way, I think a chmod is also needed, permissions on the installed system are still wrong when updating/installing a package that provides pk rules.

**Comment by philmmanjaro** [comment]
Will fix this for **rc2**.

**Comment by udeved** [comment]
I guess you need to also remove it from base group, since polkit is not base, or polkit will always be pulled in by base.

**Comment by philmmanjaro** [comment]
Then 49e1b2220a21f4c2cf0c37e246a4558120a4009b should do it ...
