### ISSUE TITLE
consider CONFIG_ACPI_REV_OVERRIDE_POSSIBLE=y for linux >4.2

### ISSUE THREAD

**Issue by oberon2007** [manjaro/packages-core#73]
There has been a [request](https://forum.manjaro.org/t/manjaro-cinnamon-17-0-1/19025/75) for this to fix battery recognition in certain Dell models.
See https://bugzilla.kernel.org/show_bug.cgi?id=105721
I think it should not do any harm, would it?

**Comment by philmmanjaro** [comment]
It seems to only affect [DELL models](https://cateee.net/lkddb/web-lkddb/ACPI_REV_OVERRIDE_POSSIBLE.html) which is also fixed by applying the latest **firmware**. I've to search some other distros, if they have enabled it. What I read so far: Fedora rejected that request in 2015.

**Comment by philmmanjaro** [comment]
Also [ARCH](https://bugs.archlinux.org/task/47710) disabled it again. So we have to check first, if a new **firmware** fixes the issue or if we need this ugly workaround.

**Comment by philmmanjaro** [comment]
Some **DELL**s have have already [Quirks](https://lkml.org/lkml/2017/3/20/735) added. So `drivers/acpi/blacklist.c` needs to be checked which they are ...

**Comment by philmmanjaro** [comment]
Seems **Ubuntu** has this option [enabled](http://kernel.ubuntu.com/~kernel-ppa/config/artful/linux/4.11.0-3.8/amd64-config.flavour.generic).

**Comment by sez11a** [comment]
I also asked for this [here](https://forum.manjaro.org/t/kernel-patch-needed-for-dell-precision-5520/21162/19?u=sez11a) a month ago. The machine I have is the same one @philmmanjaro linked to in the Quirks link above. I still get the errors upon boot even with the 4.11 kernel, and booting is a somewhat risky endeavor. Sometimes the system boots and sometimes it hangs, usually when starting SDDM. I also have updated to the latest firmware.

**Comment by oberon2007** [comment]
👍
